apps/core/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('order/', views.order, name='order'),
    path('comment/', views.comment, name='comment'),
    path('success/', views.success, name='success')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/comments/models.py
from django.db import models

# Create your models here.

apps/comments/views.py
from django.shortcuts import render

# Create your views here.

templates/comments/comment__form.html
{% load static %}
{% load i18n %}
<!-- LINKS -->
{% block links %}
<link rel="stylesheet" href="{% static 'css/comment__form.css' %}">
<script src="https://unpkg.com/imask"></script>
{% endblock %}
<!-- CONTENT -->
{% block content %}
<div class="popup__outer comment_form_popup" id="comment_form_popup">
    <div class="popup__conteiner">
        <div class="comment_form__wrapper">
            <p class="h2 upper semibold center pt64 pb32">Оставьте отзыв</p>
          
            <!-- FORM -->
            <form class="form comment_form pb64" id="comment_form" enctype="multipart/form-data" method="post">

                <!-- NAME -->
                <p>
                    <label for="comment_form_first_name">Ваше имя</label>
                    <input class="h5" name="first_name" id="comment_form_first_name" type="text" placeholder="Ваше имя" data-alert='Введите Ваше имя' required>
                </p>
                <!-- PHHONE -->
                <p>
                    <label for="comment_form_first_name">Ваше имя</label>
                    <input class="h5" name="phone" id="comment_form_phone" type="text" placeholder="Ваш номер телефона" data-alert='Введите Ваш Телефон' data-error="Телефон имеет не верный формат" required>
                </p>
                <!-- SERVICE -->
                <p>
                    <label for="comment_form_services">Услуга</label>
                    <select name="service" id="comment_form_services" required>
                        {% for service in main_service %}
                            <option value="{{ service.slug }}">{{ service.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <!-- RATE -->
                <p>
                    <label for="comment_form_rate">Оценка</label>
                    <select name="rate" id="comment_form_rate" required>
                        <option value="5" selected>Отлично</option>
                        <option value="4">Хорошо</option>
                        <option value="3">Нормально</option>
                        <option value="2">Плохо</option>
                        <option value="1">Ужасно</option>
                    </select>
                </p>
                
                <!-- TEXT -->
                <p class="textarea col-1-3">
                    <textarea 
                    class="h5" id="review-text" name="comment" id="text" 
                    data-alert='Напишите пару слов о товаре'
                    placeholder="Несколько слов о товаре..." required></textarea>
                </p>
                <p class="h6 grey col-1-3">{% trans 'Публичная оферта' %}</p>
                <!-- SUBMIT -->
                <button class="col-1-3 h5 upper comment_confirm" type="submit">{% trans 'Отправить' %}</button>
            </form>
        </div>
    </div>
</div>



<script>
    let commentForm = document.getElementById("comment_form");
    let preloader = document.getElementById('comment__preloader')
    let comments = document.querySelector('.comments_list')
    let formWrapper = document.querySelector('.comment_form__wrapper') 
    commentForm.addEventListener('submit', function(event) {
        event.preventDefault();
        // preloader.style.visibility = 'visible'
        
        formData = new FormData(commentForm);
        

        var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'core:comment'%}", false);
            xhr.setRequestHeader("X-CSRFToken",  getCookie('csrftoken') );
            xhr.onload = function(oEvent) {
                if (xhr.status == 200) {
                    let response = JSON.parse(xhr.responseText);
                    comments.innerHTML = response['html'] + comments.innerHTML
                    formWrapper.innerHTML = '<p class="h1 bold green center upper pt64 pb64">Спасибо, Ваш комментарий отправлен</p>'
                    
                } else {
                    alert('Что-то пошло не так 😞')
                }
            };

            commentForm.style.filter = 'blur(4px)';
            commentForm.style.pointerEvents =  'none';

            xhr.send(formData);
            
    }, false);

    var element = document.querySelector('input[name=phone]');
    var maskOptions = {
        mask: '+{38} (000) 000-00-00',
        lazy: false,
    };
    var mask = IMask(element, maskOptions);
</script>

{% endblock %}

templates/comments/comment__object.html
{% load static %}

<li class="comment__object">
    <div class="stars">
        {% for star in comment.rating %}
            {% if star == 0 %}
                <img src="{% static 'img/ico/star.png' %}" alt="*">
            {% else %}
                <img src="{% static 'img/ico/star_empty.png' %}" alt="*">
            {% endif %}
        {% endfor %}
    </div>
    <p class="name h5">{{ comment.name }}</p>
    <p class="date grey h6">{{ comment.datetime|date:"H:i d.M.Y" }}</p>
    <p class="text regular h5">{{ comment.text }}</p>
</li>

templates/comments/comment__stars.html
{% load static %}
<div class="stars" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
    <meta itemprop="ratingValue" content="{{ comment.stars }}">
    {% if    comment.stars > 4 and comment.stars <= 5 %}
        <img src="{% static 'img/stars-5.png' %}" alt="stars">
    {% elif  comment.stars > 3 and comment.stars <= 4 %}
        <img src="{% static 'img/stars-4.png' %}" alt="stars">
    {% elif  comment.stars > 2 and comment.stars <= 3 %}
        <img src="{% static 'img/stars-3.png' %}" alt="stars">
    {% elif  comment.stars > 1 and comment.stars <= 2 %}
        <img src="{% static 'img/stars-2.png' %}" alt="stars">
    {% elif  comment.stars > 0 and comment.stars <= 1 %}
        <img src="{% static 'img/stars-1.png' %}" alt="stars">
    {% elif  comment.stars == 0 %}
        <img src="{% static 'img/stars-0.png' %}" alt="stars">
    {% endif %}
    
</div>

templates/comments/comments.html
{% load static %}
{% load i18n %}
<!-- LINKS -->
{% block links %}
<link rel="stylesheet" href="{% static 'css/shop/product/product__comments.css' %}">
<link rel="stylesheet" href="https://unpkg.com/flexmasonry/dist/flexmasonry.css">
<script src="https://unpkg.com/flexmasonry/dist/flexmasonry.js"></script>
{% endblock %}
<div class="comments__wrapper">
    {% if not product.reviews.all %}
        <div class="wrapper">
            <p class="grey pt24 pb4">{% trans 'Пока нету отзывов' %}</p>
        </div>
    {% else %}
    <div class="comments mt32" itemprop="review" itemscope itemtype="http://schema.org/Review">
        {% include './comments__list.html' %}
    </div>
    {% endif %}
    <div class="preloader" id="comment__preloader">
        <img src="{% static 'img/preloader.gif' %}" alt="preloader">
    </div>
</div>

<!-- POP UP COMMENTS FORMS -->
{% include './comment__form.html' %}

<!-- JS -->
{% block js %}
<script>
// function Masonry() {
//     FlexMasonry.init('.comments', {
//     breakpointCols: {
//         // 'min-width: 1500px': 5,
//         // 'min-width: 1200px': 4,
//         'min-width: 960px': 2,
//         'min-width: 576px': 1,
//     },
//     responsive: true,
//     numCols: 3
// });
// }
// Masonry()
</script>
{% endblock %}

templates/comments/comments__list.html
{% load static %}
{% load i18n %}
<!-- COMMENTS -->

{% for comment in product.reviews.all %}
    <div class="wrapper">
        <!-- {{ forloop.counter }} -->
        <div class="comment">
            <meta itemprop="itemReviewed" content="{{ variant.parent.translate.name }} - {{ variant.parent.brand.name }}, {% trans 'цвет' %}: {{ variant.color.name|lower }}, {{ variant.parent.code }}">
            <div class="rating">
                <div class="stars pb8">
                    {% include './comment__stars.html' %}
                </div>
            </div>
            <div class="info">
                <div class="main">
                    <p class="user upper semibold h4 mr16" itemprop="author">{{ comment.user.first_name }}</p>
                    <p class="grey h6 pt2" itemprop="datePublished" content="{{ comment.datetime.year }}-{{ comment.datetime.month }}-{{ comment.datetime.day }}"> {{ comment.datetime }} </p>
                </div>
                {% if comment.purchase %}
                    <p class="block pt4 h6 color-3">{% trans 'Покупка подтверждена' %}</p>
                {% endif %}
            </div>
            <p class="text h5 pt12" itemprop="description">{{ comment.text }}</p>
            {% if comment.images.all|length %}
                <div class="comment__images mt16">
                    {% for image in comment.images.all %}
                        <img class="comment_image" data-src="{{ image.image_l.url }}" src="{{ image.image_xs.url }}" alt="img">
                    {% endfor %}
                </div>
            {% endif %} 
        </div>
        <!-- <div class="chat">
            <div class="message admin">
                <p class="title"><span class="grey h6">Менеджер </span><span class="upper semibold">Ростислав</span></p>
                <p class="text">Мы очень рады что вам подошло))</p>
            </div>

            <div class="message">
                <p class="title semibold upper">{{ comment.user.first_name }}</p>
                <p class="text">А есть еще такое?</p>
            </div>
        </div> -->
    </div>
{% endfor %}